[target.aarch64-linux-android]
rustflags = [
    "-C", "link-arg=-static-libstdc++",
    "-C", "link-arg=-Wl,-Bstatic",
    "-C", "link-arg=-lc++_static",
    "-C", "link-arg=-lc++abi",
    "-C", "link-arg=-Wl,-Bdynamic",
]

[target.armv7-linux-androideabi]
rustflags = ["-C", "link-arg=-static-libstdc++", "-C", "link-arg=-lc++_static"]

[target.x86_64-linux-android]
rustflags = ["-C", "link-arg=-static-libstdc++", "-C", "link-arg=-lc++_static"]
