// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../wish_parser.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'api.freezed.dart';

Future<String> initPairing({
  required int port,
  required String pairingCode,
  required String storageDir,
}) => RustLib.instance.api.crateApiApiInitPairing(
  port: port,
  pairingCode: pairingCode,
  storageDir: storageDir,
);

Future<String> getGachaLink({required int port, required String storageDir}) =>
    RustLib.instance.api.crateApiApiGetGachaLink(
      port: port,
      storageDir: storageDir,
    );

Future<String> connectToDevice({
  required String addr,
  required String storageDir,
}) => RustLib.instance.api.crateApiApiConnectToDevice(
  addr: addr,
  storageDir: storageDir,
);

Stream<ProgressUpdate> performWishImport({
  required String url,
  required String storageDir,
  required String game,
}) => RustLib.instance.api.crateApiApiPerformWishImport(
  url: url,
  storageDir: storageDir,
  game: game,
);

Future<List<BannerSummary>> getWishSummary({
  required String storageDir,
  required String game,
}) => RustLib.instance.api.crateApiApiGetWishSummary(
  storageDir: storageDir,
  game: game,
);

Future<StellarState> getCurrentState() =>
    RustLib.instance.api.crateApiApiGetCurrentState();

Stream<StellarStatus> createStatusStream() =>
    RustLib.instance.api.crateApiApiCreateStatusStream();

class StellarState {
  final StellarStatus status;
  final int? port;

  const StellarState({required this.status, this.port});

  @override
  int get hashCode => status.hashCode ^ port.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StellarState &&
          runtimeType == other.runtimeType &&
          status == other.status &&
          port == other.port;
}

@freezed
sealed class StellarStatus with _$StellarStatus {
  const StellarStatus._();

  const factory StellarStatus.idle() = StellarStatus_Idle;
  const factory StellarStatus.pairing() = StellarStatus_Pairing;
  const factory StellarStatus.paired() = StellarStatus_Paired;
  const factory StellarStatus.connecting() = StellarStatus_Connecting;
  const factory StellarStatus.connected() = StellarStatus_Connected;
  const factory StellarStatus.error(String field0) = StellarStatus_Error;
}
