// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Stream<String> createLogStream() =>
    RustLib.instance.api.crateApiApiCreateLogStream();

Future<String> initPairing({required int port, required String pairingCode}) =>
    RustLib.instance.api.crateApiApiInitPairing(
      port: port,
      pairingCode: pairingCode,
    );

Future<String> executeAdbCommand({required String command}) =>
    RustLib.instance.api.crateApiApiExecuteAdbCommand(command: command);
