// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/api.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';
import 'wish_parser.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RustStreamSink<ProgressUpdate> dco_decode_StreamSink_progress_update_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<StellarStatus> dco_decode_StreamSink_stellar_status_Sse(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  BannerSummary dco_decode_banner_summary(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_16(dynamic raw);

  @protected
  CompletedBannerInfo dco_decode_completed_banner_info(dynamic raw);

  @protected
  ExportResult dco_decode_export_result(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  FiveStarHistory dco_decode_five_star_history(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  List<BannerSummary> dco_decode_list_banner_summary(dynamic raw);

  @protected
  List<CompletedBannerInfo> dco_decode_list_completed_banner_info(dynamic raw);

  @protected
  List<FiveStarHistory> dco_decode_list_five_star_history(dynamic raw);

  @protected
  List<MonthlyStat> dco_decode_list_monthly_stat(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  MonthlyStat dco_decode_monthly_stat(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_16(dynamic raw);

  @protected
  ProgressUpdate dco_decode_progress_update(dynamic raw);

  @protected
  StellarState dco_decode_stellar_state(dynamic raw);

  @protected
  StellarStatus dco_decode_stellar_status(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RustStreamSink<ProgressUpdate> sse_decode_StreamSink_progress_update_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<StellarStatus> sse_decode_StreamSink_stellar_status_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  BannerSummary sse_decode_banner_summary(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_16(SseDeserializer deserializer);

  @protected
  CompletedBannerInfo sse_decode_completed_banner_info(
    SseDeserializer deserializer,
  );

  @protected
  ExportResult sse_decode_export_result(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  FiveStarHistory sse_decode_five_star_history(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  List<BannerSummary> sse_decode_list_banner_summary(
    SseDeserializer deserializer,
  );

  @protected
  List<CompletedBannerInfo> sse_decode_list_completed_banner_info(
    SseDeserializer deserializer,
  );

  @protected
  List<FiveStarHistory> sse_decode_list_five_star_history(
    SseDeserializer deserializer,
  );

  @protected
  List<MonthlyStat> sse_decode_list_monthly_stat(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  MonthlyStat sse_decode_monthly_stat(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_16(SseDeserializer deserializer);

  @protected
  ProgressUpdate sse_decode_progress_update(SseDeserializer deserializer);

  @protected
  StellarState sse_decode_stellar_state(SseDeserializer deserializer);

  @protected
  StellarStatus sse_decode_stellar_status(SseDeserializer deserializer);

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_progress_update_Sse(
    RustStreamSink<ProgressUpdate> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_stellar_status_Sse(
    RustStreamSink<StellarStatus> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_banner_summary(BannerSummary self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_completed_banner_info(
    CompletedBannerInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_export_result(ExportResult self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_five_star_history(
    FiveStarHistory self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_list_banner_summary(
    List<BannerSummary> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_completed_banner_info(
    List<CompletedBannerInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_five_star_history(
    List<FiveStarHistory> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_monthly_stat(
    List<MonthlyStat> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_monthly_stat(MonthlyStat self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_16(int? self, SseSerializer serializer);

  @protected
  void sse_encode_progress_update(
    ProgressUpdate self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_stellar_state(StellarState self, SseSerializer serializer);

  @protected
  void sse_encode_stellar_status(StellarStatus self, SseSerializer serializer);

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
