// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'wish_parser.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiApiInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 660309435;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_stellar',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<String> crateApiApiConnectToDevice({
    required String addr,
    required String storageDir,
  });

  Stream<StellarStatus> crateApiApiCreateStatusStream();

  Future<ExportResult> crateApiApiExportLocalJson({
    required String storageDir,
    required String game,
    required String version,
    String? uid,
    required String appVersion,
  });

  Future<StellarState> crateApiApiGetCurrentState();

  Future<String> crateApiApiGetGachaLink({
    required int port,
    required String storageDir,
  });

  Future<List<BannerSummary>> crateApiApiGetWishSummary({
    required String storageDir,
    required String game,
  });

  Future<BigInt> crateApiApiImportLocalJson({
    required String jsonContent,
    required String storageDir,
    required String game,
    String? uid,
  });

  Future<void> crateApiApiInitApp();

  Future<String> crateApiApiInitPairing({
    required int port,
    required String pairingCode,
    required String storageDir,
  });

  Stream<ProgressUpdate> crateApiApiPerformWishImport({
    required String url,
    required String storageDir,
    required String game,
  });

  Future<void> crateApiApiPreWarmAdb({required String storageDir});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<String> crateApiApiConnectToDevice({
    required String addr,
    required String storageDir,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(addr, serializer);
          sse_encode_String(storageDir, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiApiConnectToDeviceConstMeta,
        argValues: [addr, storageDir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApiConnectToDeviceConstMeta => const TaskConstMeta(
    debugName: "connect_to_device",
    argNames: ["addr", "storageDir"],
  );

  @override
  Stream<StellarStatus> crateApiApiCreateStatusStream() {
    final sink = RustStreamSink<StellarStatus>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_stellar_status_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 2,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: null,
          ),
          constMeta: kCrateApiApiCreateStatusStreamConstMeta,
          argValues: [sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiApiCreateStatusStreamConstMeta =>
      const TaskConstMeta(
        debugName: "create_status_stream",
        argNames: ["sink"],
      );

  @override
  Future<ExportResult> crateApiApiExportLocalJson({
    required String storageDir,
    required String game,
    required String version,
    String? uid,
    required String appVersion,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(storageDir, serializer);
          sse_encode_String(game, serializer);
          sse_encode_String(version, serializer);
          sse_encode_opt_String(uid, serializer);
          sse_encode_String(appVersion, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_export_result,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiApiExportLocalJsonConstMeta,
        argValues: [storageDir, game, version, uid, appVersion],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApiExportLocalJsonConstMeta => const TaskConstMeta(
    debugName: "export_local_json",
    argNames: ["storageDir", "game", "version", "uid", "appVersion"],
  );

  @override
  Future<StellarState> crateApiApiGetCurrentState() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_stellar_state,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiApiGetCurrentStateConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApiGetCurrentStateConstMeta =>
      const TaskConstMeta(debugName: "get_current_state", argNames: []);

  @override
  Future<String> crateApiApiGetGachaLink({
    required int port,
    required String storageDir,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_16(port, serializer);
          sse_encode_String(storageDir, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiApiGetGachaLinkConstMeta,
        argValues: [port, storageDir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApiGetGachaLinkConstMeta => const TaskConstMeta(
    debugName: "get_gacha_link",
    argNames: ["port", "storageDir"],
  );

  @override
  Future<List<BannerSummary>> crateApiApiGetWishSummary({
    required String storageDir,
    required String game,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(storageDir, serializer);
          sse_encode_String(game, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_banner_summary,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiApiGetWishSummaryConstMeta,
        argValues: [storageDir, game],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApiGetWishSummaryConstMeta => const TaskConstMeta(
    debugName: "get_wish_summary",
    argNames: ["storageDir", "game"],
  );

  @override
  Future<BigInt> crateApiApiImportLocalJson({
    required String jsonContent,
    required String storageDir,
    required String game,
    String? uid,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(jsonContent, serializer);
          sse_encode_String(storageDir, serializer);
          sse_encode_String(game, serializer);
          sse_encode_opt_String(uid, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_usize,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiApiImportLocalJsonConstMeta,
        argValues: [jsonContent, storageDir, game, uid],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApiImportLocalJsonConstMeta => const TaskConstMeta(
    debugName: "import_local_json",
    argNames: ["jsonContent", "storageDir", "game", "uid"],
  );

  @override
  Future<void> crateApiApiInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiApiInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApiInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<String> crateApiApiInitPairing({
    required int port,
    required String pairingCode,
    required String storageDir,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_16(port, serializer);
          sse_encode_String(pairingCode, serializer);
          sse_encode_String(storageDir, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiApiInitPairingConstMeta,
        argValues: [port, pairingCode, storageDir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApiInitPairingConstMeta => const TaskConstMeta(
    debugName: "init_pairing",
    argNames: ["port", "pairingCode", "storageDir"],
  );

  @override
  Stream<ProgressUpdate> crateApiApiPerformWishImport({
    required String url,
    required String storageDir,
    required String game,
  }) {
    final sink = RustStreamSink<ProgressUpdate>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_progress_update_Sse(sink, serializer);
            sse_encode_String(url, serializer);
            sse_encode_String(storageDir, serializer);
            sse_encode_String(game, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 10,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_AnyhowException,
          ),
          constMeta: kCrateApiApiPerformWishImportConstMeta,
          argValues: [sink, url, storageDir, game],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiApiPerformWishImportConstMeta =>
      const TaskConstMeta(
        debugName: "perform_wish_import",
        argNames: ["sink", "url", "storageDir", "game"],
      );

  @override
  Future<void> crateApiApiPreWarmAdb({required String storageDir}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(storageDir, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiApiPreWarmAdbConstMeta,
        argValues: [storageDir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApiPreWarmAdbConstMeta =>
      const TaskConstMeta(debugName: "pre_warm_adb", argNames: ["storageDir"]);

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<ProgressUpdate> dco_decode_StreamSink_progress_update_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<StellarStatus> dco_decode_StreamSink_stellar_status_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  BannerSummary dco_decode_banner_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 12)
      throw Exception('unexpected arr length: expect 12 but see ${arr.length}');
    return BannerSummary(
      title: dco_decode_String(arr[0]),
      pity: dco_decode_i_32(arr[1]),
      last5Star: dco_decode_String(arr[2]),
      last5StarPity: dco_decode_i_32(arr[3]),
      isGuaranteed: dco_decode_bool(arr[4]),
      totalWishes: dco_decode_i_32(arr[5]),
      history5Star: dco_decode_list_five_star_history(arr[6]),
      history4Star: dco_decode_list_five_star_history(arr[7]),
      avgPity: dco_decode_f_64(arr[8]),
      total4Star: dco_decode_i_32(arr[9]),
      pity4Star: dco_decode_i_32(arr[10]),
      monthlyStats: dco_decode_list_monthly_stat(arr[11]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  int dco_decode_box_autoadd_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  CompletedBannerInfo dco_decode_completed_banner_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return CompletedBannerInfo(
      gachaType: dco_decode_String(arr[0]),
      entriesCount: dco_decode_usize(arr[1]),
    );
  }

  @protected
  ExportResult dco_decode_export_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return ExportResult(
      content: dco_decode_String(arr[0]),
      fileName: dco_decode_String(arr[1]),
    );
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  FiveStarHistory dco_decode_five_star_history(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return FiveStarHistory(
      name: dco_decode_String(arr[0]),
      pity: dco_decode_i_32(arr[1]),
      time: dco_decode_String(arr[2]),
      isStandard: dco_decode_bool(arr[3]),
      itemType: dco_decode_String(arr[4]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<BannerSummary> dco_decode_list_banner_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_banner_summary).toList();
  }

  @protected
  List<CompletedBannerInfo> dco_decode_list_completed_banner_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_completed_banner_info)
        .toList();
  }

  @protected
  List<FiveStarHistory> dco_decode_list_five_star_history(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_five_star_history).toList();
  }

  @protected
  List<MonthlyStat> dco_decode_list_monthly_stat(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_monthly_stat).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  MonthlyStat dco_decode_monthly_stat(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return MonthlyStat(
      year: dco_decode_i_32(arr[0]),
      month: dco_decode_i_32(arr[1]),
      totalPulls: dco_decode_i_32(arr[2]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_16(raw);
  }

  @protected
  ProgressUpdate dco_decode_progress_update(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return ProgressUpdate(
      gachaType: dco_decode_String(arr[0]),
      currentPage: dco_decode_u_32(arr[1]),
      totalEntriesFetched: dco_decode_usize(arr[2]),
      completedBannerDetails: dco_decode_list_completed_banner_info(arr[3]),
    );
  }

  @protected
  StellarState dco_decode_stellar_state(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return StellarState(
      status: dco_decode_stellar_status(arr[0]),
      port: dco_decode_opt_box_autoadd_u_16(arr[1]),
    );
  }

  @protected
  StellarStatus dco_decode_stellar_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return StellarStatus_Idle();
      case 1:
        return StellarStatus_Pairing();
      case 2:
        return StellarStatus_Paired();
      case 3:
        return StellarStatus_Connecting();
      case 4:
        return StellarStatus_Connected();
      case 5:
        return StellarStatus_Error(dco_decode_String(raw[1]));
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<ProgressUpdate> sse_decode_StreamSink_progress_update_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<StellarStatus> sse_decode_StreamSink_stellar_status_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  BannerSummary sse_decode_banner_summary(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_title = sse_decode_String(deserializer);
    var var_pity = sse_decode_i_32(deserializer);
    var var_last5Star = sse_decode_String(deserializer);
    var var_last5StarPity = sse_decode_i_32(deserializer);
    var var_isGuaranteed = sse_decode_bool(deserializer);
    var var_totalWishes = sse_decode_i_32(deserializer);
    var var_history5Star = sse_decode_list_five_star_history(deserializer);
    var var_history4Star = sse_decode_list_five_star_history(deserializer);
    var var_avgPity = sse_decode_f_64(deserializer);
    var var_total4Star = sse_decode_i_32(deserializer);
    var var_pity4Star = sse_decode_i_32(deserializer);
    var var_monthlyStats = sse_decode_list_monthly_stat(deserializer);
    return BannerSummary(
      title: var_title,
      pity: var_pity,
      last5Star: var_last5Star,
      last5StarPity: var_last5StarPity,
      isGuaranteed: var_isGuaranteed,
      totalWishes: var_totalWishes,
      history5Star: var_history5Star,
      history4Star: var_history4Star,
      avgPity: var_avgPity,
      total4Star: var_total4Star,
      pity4Star: var_pity4Star,
      monthlyStats: var_monthlyStats,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  int sse_decode_box_autoadd_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_16(deserializer));
  }

  @protected
  CompletedBannerInfo sse_decode_completed_banner_info(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_gachaType = sse_decode_String(deserializer);
    var var_entriesCount = sse_decode_usize(deserializer);
    return CompletedBannerInfo(
      gachaType: var_gachaType,
      entriesCount: var_entriesCount,
    );
  }

  @protected
  ExportResult sse_decode_export_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_content = sse_decode_String(deserializer);
    var var_fileName = sse_decode_String(deserializer);
    return ExportResult(content: var_content, fileName: var_fileName);
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  FiveStarHistory sse_decode_five_star_history(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_pity = sse_decode_i_32(deserializer);
    var var_time = sse_decode_String(deserializer);
    var var_isStandard = sse_decode_bool(deserializer);
    var var_itemType = sse_decode_String(deserializer);
    return FiveStarHistory(
      name: var_name,
      pity: var_pity,
      time: var_time,
      isStandard: var_isStandard,
      itemType: var_itemType,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<BannerSummary> sse_decode_list_banner_summary(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <BannerSummary>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_banner_summary(deserializer));
    }
    return ans_;
  }

  @protected
  List<CompletedBannerInfo> sse_decode_list_completed_banner_info(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <CompletedBannerInfo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_completed_banner_info(deserializer));
    }
    return ans_;
  }

  @protected
  List<FiveStarHistory> sse_decode_list_five_star_history(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <FiveStarHistory>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_five_star_history(deserializer));
    }
    return ans_;
  }

  @protected
  List<MonthlyStat> sse_decode_list_monthly_stat(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <MonthlyStat>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_monthly_stat(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  MonthlyStat sse_decode_monthly_stat(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_year = sse_decode_i_32(deserializer);
    var var_month = sse_decode_i_32(deserializer);
    var var_totalPulls = sse_decode_i_32(deserializer);
    return MonthlyStat(
      year: var_year,
      month: var_month,
      totalPulls: var_totalPulls,
    );
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_16(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ProgressUpdate sse_decode_progress_update(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_gachaType = sse_decode_String(deserializer);
    var var_currentPage = sse_decode_u_32(deserializer);
    var var_totalEntriesFetched = sse_decode_usize(deserializer);
    var var_completedBannerDetails = sse_decode_list_completed_banner_info(
      deserializer,
    );
    return ProgressUpdate(
      gachaType: var_gachaType,
      currentPage: var_currentPage,
      totalEntriesFetched: var_totalEntriesFetched,
      completedBannerDetails: var_completedBannerDetails,
    );
  }

  @protected
  StellarState sse_decode_stellar_state(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_status = sse_decode_stellar_status(deserializer);
    var var_port = sse_decode_opt_box_autoadd_u_16(deserializer);
    return StellarState(status: var_status, port: var_port);
  }

  @protected
  StellarStatus sse_decode_stellar_status(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        return StellarStatus_Idle();
      case 1:
        return StellarStatus_Pairing();
      case 2:
        return StellarStatus_Paired();
      case 3:
        return StellarStatus_Connecting();
      case 4:
        return StellarStatus_Connected();
      case 5:
        var var_field0 = sse_decode_String(deserializer);
        return StellarStatus_Error(var_field0);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_progress_update_Sse(
    RustStreamSink<ProgressUpdate> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_progress_update,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_stellar_status_Sse(
    RustStreamSink<StellarStatus> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_stellar_status,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_banner_summary(BannerSummary self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.title, serializer);
    sse_encode_i_32(self.pity, serializer);
    sse_encode_String(self.last5Star, serializer);
    sse_encode_i_32(self.last5StarPity, serializer);
    sse_encode_bool(self.isGuaranteed, serializer);
    sse_encode_i_32(self.totalWishes, serializer);
    sse_encode_list_five_star_history(self.history5Star, serializer);
    sse_encode_list_five_star_history(self.history4Star, serializer);
    sse_encode_f_64(self.avgPity, serializer);
    sse_encode_i_32(self.total4Star, serializer);
    sse_encode_i_32(self.pity4Star, serializer);
    sse_encode_list_monthly_stat(self.monthlyStats, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_16(self, serializer);
  }

  @protected
  void sse_encode_completed_banner_info(
    CompletedBannerInfo self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.gachaType, serializer);
    sse_encode_usize(self.entriesCount, serializer);
  }

  @protected
  void sse_encode_export_result(ExportResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.content, serializer);
    sse_encode_String(self.fileName, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_five_star_history(
    FiveStarHistory self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_i_32(self.pity, serializer);
    sse_encode_String(self.time, serializer);
    sse_encode_bool(self.isStandard, serializer);
    sse_encode_String(self.itemType, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_banner_summary(
    List<BannerSummary> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_banner_summary(item, serializer);
    }
  }

  @protected
  void sse_encode_list_completed_banner_info(
    List<CompletedBannerInfo> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_completed_banner_info(item, serializer);
    }
  }

  @protected
  void sse_encode_list_five_star_history(
    List<FiveStarHistory> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_five_star_history(item, serializer);
    }
  }

  @protected
  void sse_encode_list_monthly_stat(
    List<MonthlyStat> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_monthly_stat(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_monthly_stat(MonthlyStat self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.year, serializer);
    sse_encode_i_32(self.month, serializer);
    sse_encode_i_32(self.totalPulls, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_16(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_16(self, serializer);
    }
  }

  @protected
  void sse_encode_progress_update(
    ProgressUpdate self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.gachaType, serializer);
    sse_encode_u_32(self.currentPage, serializer);
    sse_encode_usize(self.totalEntriesFetched, serializer);
    sse_encode_list_completed_banner_info(
      self.completedBannerDetails,
      serializer,
    );
  }

  @protected
  void sse_encode_stellar_state(StellarState self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_stellar_status(self.status, serializer);
    sse_encode_opt_box_autoadd_u_16(self.port, serializer);
  }

  @protected
  void sse_encode_stellar_status(StellarStatus self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case StellarStatus_Idle():
        sse_encode_i_32(0, serializer);
      case StellarStatus_Pairing():
        sse_encode_i_32(1, serializer);
      case StellarStatus_Paired():
        sse_encode_i_32(2, serializer);
      case StellarStatus_Connecting():
        sse_encode_i_32(3, serializer);
      case StellarStatus_Connected():
        sse_encode_i_32(4, serializer);
      case StellarStatus_Error(field0: final field0):
        sse_encode_i_32(5, serializer);
        sse_encode_String(field0, serializer);
    }
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }
}
