// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class BannerSummary {
  final String title;
  final int pity;
  final String last5Star;
  final int last5StarPity;
  final bool isGuaranteed;
  final int totalWishes;
  final List<FiveStarHistory> history5Star;
  final double avgPity;
  final int total4Star;
  final int pity4Star;

  const BannerSummary({
    required this.title,
    required this.pity,
    required this.last5Star,
    required this.last5StarPity,
    required this.isGuaranteed,
    required this.totalWishes,
    required this.history5Star,
    required this.avgPity,
    required this.total4Star,
    required this.pity4Star,
  });

  @override
  int get hashCode =>
      title.hashCode ^
      pity.hashCode ^
      last5Star.hashCode ^
      last5StarPity.hashCode ^
      isGuaranteed.hashCode ^
      totalWishes.hashCode ^
      history5Star.hashCode ^
      avgPity.hashCode ^
      total4Star.hashCode ^
      pity4Star.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BannerSummary &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          pity == other.pity &&
          last5Star == other.last5Star &&
          last5StarPity == other.last5StarPity &&
          isGuaranteed == other.isGuaranteed &&
          totalWishes == other.totalWishes &&
          history5Star == other.history5Star &&
          avgPity == other.avgPity &&
          total4Star == other.total4Star &&
          pity4Star == other.pity4Star;
}

class CompletedBannerInfo {
  final String gachaType;
  final BigInt entriesCount;

  const CompletedBannerInfo({
    required this.gachaType,
    required this.entriesCount,
  });

  @override
  int get hashCode => gachaType.hashCode ^ entriesCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CompletedBannerInfo &&
          runtimeType == other.runtimeType &&
          gachaType == other.gachaType &&
          entriesCount == other.entriesCount;
}

class FiveStarHistory {
  final String name;
  final int pity;
  final String time;

  const FiveStarHistory({
    required this.name,
    required this.pity,
    required this.time,
  });

  @override
  int get hashCode => name.hashCode ^ pity.hashCode ^ time.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FiveStarHistory &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          pity == other.pity &&
          time == other.time;
}

class ProgressUpdate {
  final String gachaType;
  final int currentPage;
  final BigInt totalEntriesFetched;
  final List<CompletedBannerInfo> completedBannerDetails;

  const ProgressUpdate({
    required this.gachaType,
    required this.currentPage,
    required this.totalEntriesFetched,
    required this.completedBannerDetails,
  });

  @override
  int get hashCode =>
      gachaType.hashCode ^
      currentPage.hashCode ^
      totalEntriesFetched.hashCode ^
      completedBannerDetails.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProgressUpdate &&
          runtimeType == other.runtimeType &&
          gachaType == other.gachaType &&
          currentPage == other.currentPage &&
          totalEntriesFetched == other.totalEntriesFetched &&
          completedBannerDetails == other.completedBannerDetails;
}
